version: '3.7'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'housfy2'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  phpunit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'housfy_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  cache:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped

