version: '3.7'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  app:
    container_name: housfy_web
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'housfy2'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  phpunit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  cache:
    container_name: redis_housfy
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    # MySQL container
  db:
    image: mariadb
    container_name: housfy_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      DB_HOST: 'localhost'
      MYSQL_DATABASE: 'housfy_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_housfy
      restart: always
      ports:
        - 8086:80
      depends_on:
        - db
